AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  LayerName:
    Description: Lambda layer name
    Default: slack-webhook-nodejs
    Type: String
  AllowPublic:
    Description: Whether to share your Lambda layer to all AWS accounts
    Default: false
    Type: String
    AllowedValues: [true, false]

Conditions:
  ShouldPublic:
    !Equals [!Ref AllowPublic, true]

Resources:
  SlackWebhookLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Ref LayerName
      Description: '@slack/webhook AWS Lambda layer'
      ContentUri: layer/
      CompatibleRuntimes:
        - nodejs14.x
        - nodejs16.x
        - nodejs18.x
        - nodejs20.x
      RetentionPolicy: Retain
      LicenseInfo: MIT
    Metadata:
      BuildMethod: makefile
  SlackWebhookLayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Condition: ShouldPublic
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref SlackWebhookLayer
      Principal: '*'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

Outputs:
  LayerVersion:
    Description: The ARN of Lambda Layer
    Value: !Ref SlackWebhookLayer

Metadata:
  AWS::ServerlessRepo::Application:
    Name: lambda-layer-slack-webhook-nodejs
    Description: '@slack/webhook AWS Lambda layer'
    Author: elastic-infra
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - lambda
      - layer
      - nodejs
    HomePageUrl: https://github.com/elastic-infra/lambda-layer-slack-webhook-nodejs
    SemanticVersion: 1.1.0
    SourceCodeUrl: https://github.com/elastic-infra/lambda-layer-slack-webhook-nodejs
